AWSTemplateFormatVersion: '2010-09-09'
Description: Create an EC2 instance with a security group that allows SSH access and a new key pair

Resources:
  MyEC2Instance:
    Type: 'AWS::EC2::Instance'
    Properties: 
      InstanceType: t2.micro
      ImageId: ami-0fff1b9a61dec8a5f
      KeyName: !Ref SshKeyPair
      SecurityGroups:
        - !Ref SshSecurityGroup

  SshSecurityGroup:
    Type: 'AWS::EC2::SecurityGroup'
    Properties:
      GroupDescription: Enable SSH access
      SecurityGroupIngress:
        - IpProtocol: tcp
          FromPort: '22'
          ToPort: '22'
          CidrIp: 0.0.0.0/0

  SshKeyPair:
    Type: 'AWS::EC2::KeyPair'
    Properties:
      KeyName: key-pair-lab1 

Outputs:
  KeyPairName:
    Description: The name of the key pair
    Value: !Ref SshKeyPair
