AWSTemplateFormatVersion: "2010-09-09"
Description: Create an EC2 instance with a security group that allows SSH access and a new key pair

Resources:

  MyEC2Instance:
    Type: "AWS::EC2::Instance"
    Properties:
      InstanceType: t2.micro
      SubnetId: !ImportValue PublicSubnetId
      ImageId: ami-00385a401487aefa4
      SecurityGroupIds:
        - !ImportValue  SshJumpboxSecurityGroupId


