AWSTemplateFormatVersion: "2010-09-09"
Description: AWS CloudFormation to Create a VPC, subnets and networking - IaC CA 1

Resources:
  # create VPC
  VpcCa1:
    Type: AWS::EC2::VPC
    Properties:
      CidrBlock: 10.0.0.0/22
      EnableDnsSupport: true
      EnableDnsHostnames: true
      Tags:
        - Key: Name
          Value: VpcCa1

  # create public subnet
  PublicSubnteCa1:
    Type: AWS::EC2::Subnet
    Properties:
      VpcId: !Ref VpcCa1
      CidrBlock: 10.0.1.0/24
      MapPublicIpOnLaunch: true
      Tags:
        - Key: Name
          Value: PublicSubnteCa1

  # create private subnet
  PrivateSubnteCa1:
    Type: AWS::EC2::Subnet
    Properties:
      VpcId: !Ref VpcCa1
      CidrBlock: 10.0.2.0/24
      MapPublicIpOnLaunch: false
      Tags:
        - Key: Name
          Value: PrivateSubnteCa1

  # create internet gateway
  InternetGatewayCa1:
    Type: AWS::EC2::InternetGateway
    Properties:
      Tags:
        - Key: Name
          Value: InternetGatewayCa1

  # attach gateway to VPC
  AttachGatewayCa1:
    Type: AWS::EC2::VPCGatewayAttachment
    Properties:
      VpcId: !Ref VpcCa1
      InternetGatewayId: !Ref InternetGatewayCa1

  # create route table
  PublicRouteTableCa1:
    Type: AWS::EC2::RouteTable
    Properties:
      VpcId: !Ref VpcCa1
      Tags:
        - Key: Name
          Value: PublicRouteTableCa1
  # create route frin route table to internet gateway
  PublicRouteCa1:
    Type: AWS::EC2::Route
    Properties:
      RouteTableId: !Ref PublicRouteTableCa1
      DestinationCidrBlock: 0.0.0.0/0
      GatewayId: !Ref InternetGatewayCa1

  # connect public subnet to route table
  PublicSubnetRouteTableAssociationCa1:
    Type: AWS::EC2::SubnetRouteTableAssociation
    Properties:
      SubnetId: !Ref PublicSubnteCa1
      RouteTableId: !Ref PublicRouteTableCa1

  ElasticIpCa1:
    Type: AWS::EC2::EIP
    Properties:
      Domain: vpc

Outputs:
  VpcId:
    Description: The VPC ID
    Value: !Ref VpcCa1
    Export:
      Name: VpcId

  PublicSubnetId:
    Description: The public subnet ID
    Value: !Ref PublicSubnteCa1
    Export:
      Name: PublicSubnetId

  PrivateSubnetId:
    Description: The private subnet ID
    Value: !Ref PrivateSubnteCa1
    Export:
      Name: PrivateSubnetId

  CurrentRegion:
    Description: The AWS region where the stack is deployed
    Value: !Ref AWS::Region
    Export:
      Name: CurrentRegion
  
  ElasticIpId:
    Description: The Elastic IP ID
    Value: !GetAtt  ElasticIpCa1.AllocationId
    Export:
      Name: ElasticIpId
